language: haskell

ghc: 7.8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz

script:
  - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
